#!/usr/bin/env bash
set -u
BASE=weibo_forensics_5323616788681841
UA_DESK='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/126 Safari/537.36'
UA_MOB='Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Weibo'
echo 'utc_time,url,method,user_agent,status,redirect_chain,content_type,size,sha256,local_path,login_required,independent_review' > $BASE/evidence/evidence.csv
fetch(){ url="$1"; method="$2"; follow="$3"; uan="$4"; ua="$UA_DESK"; [ "$uan" = mobile ] && ua="$UA_MOB"; ts=$(date -u +%Y%m%dT%H%M%SZ); safe=$(echo "$url"|sed 's#[^A-Za-z0-9_.-]#_#g'|cut -c1-100); out="$BASE/raw/http/${ts}_${safe}_${method}_${uan}_${follow}.body"; hdr="$BASE/raw/http/${ts}_${safe}_${method}_${uan}_${follow}.headers"; opts=(-sS -D "$hdr" -o "$out" -X "$method" -A "$ua" -w '%{http_code}|%{url_effective}|%{content_type}|%{size_download}|%{redirect_url}') ; [ "$follow" = follow ] && opts=(-L "${opts[@]}"); curl "${opts[@]}" "$url" > /tmp/curlmeta 2>>$BASE/evidence/curl_errors.log || true; meta=$(cat /tmp/curlmeta); status=${meta%%|*}; rest=${meta#*|}; final=${rest%%|*}; rest=${rest#*|}; ctype=${rest%%|*}; rest=${rest#*|}; size=${rest%%|*}; sha=$(sha256sum "$out"|awk '{print $1}'); chain=$(awk 'BEGIN{ORS=" > "}/^HTTP/{next}/^[Ll]ocation:/{print $2}' "$hdr" | tr -d '\r'); printf '"%s","%s","%s","%s","%s","%s%s","%s","%s","%s","%s","unknown","yes/partial"\n' "$ts" "$url" "$method" "$uan" "$status" "$chain" "$final" "$ctype" "$size" "$sha" "$out" >> $BASE/evidence/evidence.csv; }
urls=( 'https://m.weibo.cn/detail/5323616788681841' 'https://www.sina.cn/news/detail/5323616788681841.html' 'https://www.sina.cn/media/8345249001' 'https://www.sina.cn/news/detail/5318734828801903.html' 'http://t.cn/AX9xdpfY' 'https://t.cn/AX9xdpfY' 'https://video.weibo.com/show?fid=1034:5323616443629696' 'https://weibo.com/tv/show/1034:5323616443629696' 'https://www.sina.cn/media/1749821214' 'https://www.bilibili.com/video/BV1Yu3T6zEeJ' 'https://www.bilibili.com/video/BV1KD3g6uE6t' 'https://www.zhihu.com/question/2066003943059203398' )
: > $BASE/evidence/urls.txt
for u in "${urls[@]}"; do echo "$u" >> $BASE/evidence/urls.txt; for m in GET HEAD; do for f in nofollow follow; do for ua in desktop mobile; do fetch "$u" "$m" "$f" "$ua"; done; done; done; done
# archive CDX
for u in "${urls[@]}"; do enc=$(python3 -c 'import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1],safe=""))' "$u"); for a in "https://web.archive.org/cdx?url=$enc&output=json&fl=timestamp,original,statuscode,mimetype,digest" "https://arquivo.pt/wayback/cdx?url=$enc&output=json" "https://archive.today/$u"; do echo "$a" >> $BASE/evidence/urls.txt; fetch "$a" GET follow desktop; done; done
find $BASE -type f ! -path '*/hashes.sha256' -print0|sort -z|xargs -0 sha256sum > $BASE/evidence/hashes.sha256
